---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cashe: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distibution == "Ubuntu"

  - name: add PHP support for apache
    apt:
      name: libapache-mod-php
    when: ansible_distribution == "Ubuntu"

